<?php  if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Yield  ::  HOOKS
 *
 * Adds layout support :: Similar to RoR <%= yield =>
 * '{yield}' will be replaced with all output generated by the controller/view.
*/
class Yield
{
  function doYield()
  {
    global $OUT;
  
    $CI =& get_instance();
    if (!is_object($CI)):
      show_error('An application error ocurred.', 500);
      return;
    endif;

    $output = $CI->output->get_output();
    
    if (isset($CI->layout))
    {
      if (!preg_match('/(.+).php$/', $CI->layout))
      {
        $CI->layout .= '.php';
      }

      $requested = APPPATH . 'views/layouts/' . $CI->layout;
      $default = APPPATH . 'views/layouts/default.php';
      
      if (file_exists($requested))
      {
        $layout = $CI->load->file($requested, true);
        $view = str_replace("{yield}", $output, $layout);
      }
      else
      { die($default);
        $layout = $CI->load->file($default, true);
        $view = str_replace("{yield}", $output, $layout);
      }
    }
    else
    {
      $view = $output;
    }
    
    $OUT->_display($view);
  }
}